spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chaeso?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234



  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        dialect:
          storage_engine: innodb
