cloud:
  aws:
    credentials:
      access-key: AKIAYFV5CBZNVUKV42E7
      secret-key: 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
    region:
      static: ap-northeast-2
    stack:
      auto: false
    s3:
      bucket: chaeso-s3-bucket