spring:
  config:
    activate:
      on-profile: db
  datasource:
    url: jdbc:mysql://chaeso-rds.cjr4zeaxosnc.ap-northeast-2.rds.amazonaws.com/chaeso
    username: chaeso
    password: Chaeso1!
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        dialect:
          storage_engine: innodb
